import { prisma } from '@/lib/prisma';
import { getProfileController } from '../profile/model';

export async function getOwnedProperties() {
    try {
        const { data: user, error, status } = await getProfileController();

        if (error || !user) {
             return { error: error || 'User not found', status: status || 404 };
        }

        const properties = await prisma.property.findMany({
            where: { landlordId: user.id },
            orderBy: { createdAt: 'desc' },
            include: {
                PropertyImage: true
            }
        });

        return { data: properties, status: 200 };

    } catch (error) {
        console.error('Error fetching owned properties:', error);
        return { error: 'Internal Server Error', status: 500 };
    }
}

export async function createProperty(data: any, userId: string) {
    try {
        // Ensure Landlord record exists for this user, regardless of role
        // This effectively "promotes" them or just satisfies the FK constraint
        await prisma.landlord.upsert({
            where: { id: userId },
            create: { id: userId },
            update: {}
        });

        const property = await prisma.property.create({
            data: {
                // propertyId is autogenerated
                landlordId: userId,
                title: data.title,
                description: data.description,
                type: data.type,
                address: data.address,
                city: data.city,
                state: data.state,
                zipCode: data.zipCode,
                pricePerMonth: data.pricePerMonth,
                area: data.area,
                
                division: data.division,
                district: data.district,
                thana: data.thana,
                subArea: data.subArea,
                shortAddress: data.shortAddress,
                latitude: data.latitude,
                longitude: data.longitude,
                
                utilitiesIncluded: data.utilitiesIncluded,
                
                bedrooms: data.bedrooms,
                bathrooms: data.bathrooms,
                balcony: data.balcony,
                floorNo: data.floorNo,
                
                maxGuests: data.maxGuests,
                status: 'DRAFT',
                updatedAt: new Date(),
                PropertyImage: {
                    create: data.images?.map((url: string, index: number) => ({
                        // imageId is autogenerated
                        imageUrl: url,
                        displayOrder: index,
                        isPrimary: index === 0
                    }))
                }
            }
        });

        return { data: property, status: 201 };
    } catch (error) {
        console.error('Error creating property:', error);
        return { error: 'Internal Server Error', status: 500 };
    }
}

export async function updateProperty(propertyId: string, data: any, userId: string) {
    try {
        const { images, ...updates } = data;

        // Verify ownership
        const property = await prisma.property.findUnique({
            where: { id: propertyId },
        });

        if (!property) {
            return { error: 'Property not found', status: 404 };
        }

        if (property.landlordId !== userId) {
             return { error: 'Unauthorized to edit this property', status: 403 };
        }
        
        // Handle Images
        if (images && Array.isArray(images)) {
            await prisma.propertyImage.deleteMany({
                where: { propertyId }
            });

            if (images.length > 0) {
                await prisma.propertyImage.createMany({
                    data: images.map((url: string, index: number) => ({
                        // imageId is autogenerated
                        imageUrl: url,
                        propertyId: propertyId,
                        displayOrder: index,
                        isPrimary: index === 0
                    }))
                });
            }
        }

        const updated = await prisma.property.update({
            where: { id: propertyId },
            data: {
                updatedAt: new Date(),
                title: updates.title,
                description: updates.description,
                type: updates.type,
                address: updates.address,
                city: updates.city,
                state: updates.state,
                zipCode: updates.zipCode,
                pricePerMonth: updates.pricePerMonth,
                
                division: updates.division,
                district: updates.district,
                thana: updates.thana,
                subArea: updates.subArea,
                shortAddress: updates.shortAddress,
                latitude: updates.latitude,
                longitude: updates.longitude,
                
                utilitiesIncluded: updates.utilitiesIncluded,
                
                bedrooms: updates.bedrooms,
                bathrooms: updates.bathrooms,
                balcony: updates.balcony,
                floorNo: updates.floorNo,
                area: updates.area, 
                
                maxGuests: updates.maxGuests,
            }
        });

        return { data: updated, status: 200 };
    } catch (error) {
        console.error('Error updating property:', error);
        return { error: 'Internal Server Error', status: 500 };
    }
}

export async function deleteProperty(propertyId: string, userId: string) {
    try {
        // Verify ownership
        const property = await prisma.property.findUnique({
             where: { id: propertyId },
        });

        if (!property) {
             return { error: 'Property not found', status: 404 };
        }

        if (property.landlordId !== userId) {
             return { error: 'Unauthorized to delete this property', status: 403 };
        }

        await prisma.property.delete({
            where: { id: propertyId }
        });

        return { success: true, status: 200 };
    } catch (error) {
        console.error('Error deleting property:', error);
        return { error: 'Internal Server Error', status: 500 };
    }
}
